### ISSUE TITLE
[axe-core-rspec] 4.1 -> 4.2  undefined method `find_elements' for #<WebDriverScriptAdapter::FrameAdapter::WatirAdapter

### ISSUE THREAD

**Issue by tommeier** [dequelabs/axe-core-gems#191]
<pre>
<code>
- `axe-core-rspec (4.2.0)` was working on 4.1.0
</code>
</pre>

Error: 

```
undefined method `find_elements' for #<WebDriverScriptAdapter::FrameAdapter::WatirAdapter:0x00007fb1464f54a8>
```

On callee: 

```
expect(entry_point).to be_axe_clean.according_to(:wcag2a, :wcag2aa)
```

Upgrading from 4.1 to 4.2.

as part of upgrade watir went to (6.19.1) - from 6.19.0. Is there a locked dep missing?

**Comment by tommeier** [comment]
still an issue on 4.3 

![image](https://user-images.githubusercontent.com/19973/134256403-e6e36392-787e-473c-85bd-8d4e191b8235.png)

**Comment by michael-siek** [comment]
Hey @tommeier just following up to see if this is still an issue with axe-core-gems version 4.8.1.

**Comment by tommeier** [comment]
@michael-siek was a few years ago now and I'm no longer in a codebase utilising axe-core-rspec - it was when I left :)
