### ISSUE TITLE
NoMethodError: undefined method `execute_script' for #<Capybara::Cuprite::Browser:0x00005646aaca3770>

### ISSUE THREAD

**Issue by khiga8** [dequelabs/axe-core-gems#243]
Hi team, 

We are trying to upgrade our `axe-core-api` version from 4.2 to 4.4.1. Here is the [related PR](https://github.com/primer/view_components/pull/1333).

However, we're blocked due to this  [new error that emerges](https://github.com/primer/view_components/runs/7984796200?check_suite_focus=true):

```
undefined method `execute_script' for #<Capybara::Cuprite::Browser:0x00005646aaca3770>
```

I've ran into the same error when bumping to 4.3 and traced it down to this PR: https://github.com/dequelabs/axe-core-gems/pull/199 which introduces some changes related to `ExecEvalScriptAdapter2`.

Stack trace:
```
NoMethodError: undefined method `execute_script' for #<Capybara::Cuprite::Browser:0x00005646aaca3770>
    /workspaces/view_components/vendor/bundle/ruby/2.7.0/gems/axe-core-api-4.3.2/lib/webdriver_script_adapter/exec_eval_script_adapter.rb:35:in `execute_script_fixed'
```

Any advice for how we can resolve this? We use the `Cuprite` driver. We don't have any issues with versions 4.3.

**Comment by uday708** [comment]
I am also getting `undefined method execute_script for #<Capybara::Poltergeist::Browser:0x4be8d40e> error with axe-core-rspec v4.0.0`, can someone help me here for any solution.

**Comment by nialbima** [comment]
I'm having this issue when migrating our system specs to Cuprite. From what I can tell, it's because this method changes the page target to `page.driver.browser`, which is a Capybara::Cuprite::Browser object:
```
      def get_selenium(page)
        page = page.driver if page.respond_to?("driver")
        page = page.browser if page.respond_to?("browser") and not page.browser.is_a?(::Symbol)
        page
      end
```

Doing something gross like monkey-patching the method in doesn't fix the issue. That leads to some other weirdness, and I've now lost a full day to poking at this and need to abandon this migration. If anybody has any tips, I'm ten-thousand-percent ears.

**Comment by khiga8** [comment]
@uday708 and @nialbima, I never resolved this issue.

> I've now lost a full day to poking at this and need to abandon this migration

This happened to me too. I thought it could be a simple update but it didn't turn out that way...

I followed up with the axe team on their Slack group and they mentioned that their code now assumes the driver is selenium, and that adding cuprite support might involve a new package altogether. I've put aside this migration effort for now since our team is considering a move away from `cuprite`, but perhaps you can follow up with them.

[Here's the Slack message](https://axecommunity.slack.com/archives/C01BSF8J6LS/p1661384939042349) in the axe community slack group.

**Comment by nialbima** [comment]
@khiga8 Thanks for the link! At this point, it seems like I'm going to be yelling at Selenium for the rest of my career 🙃. If you guys wind up deciding to stick with Cuprite and developing a new gem, I'd be open to contributing.

**Comment by camertron** [comment]
I looked into this today and was able to get things working via these three monkeypatches:

```ruby
module Capybara
  class Session
    alias_method :execute_async_script, :evaluate_async_script
  end

  module Cuprite
    class Browser
      alias_method :execute_async_script, :evaluate_async
    end
  end
end

module Ferrum
  class Frame
    module Runtime
      prepend Module.new {
        def evaluate_async(expression, *args)
          super(expression, 10 * 1000, *args)
        end
      }
    end
  end
end
```

To be clear: I don't think anyone should actually _use_ these, but I thought I'd comment here for posterity and in case it helps with any future work.

**Comment by adam-h** [comment]
Sadly this now fails in more places with latest axe-core-rspec (4.9.0) and cuprite (0.15.1).

I tried extending @camertron's patch to provide the `browser.manage.timeouts.page_load` getter/setter and the `browser.execute_script` method but hit a JS syntax error from Ferrum:

```
Ferrum::JavaScriptError:
       SyntaxError: Unexpected token 'const'
```

---

It's not working, but here's the patch I used to get this far:

```rb
module Capybara
  class Session
    alias_method :execute_async_script, :evaluate_async_script
  end

  module Cuprite
    class Browser
      alias_method :execute_async_script, :evaluate_async
      alias_method :execute_script, :evaluate

      def manage
        @manage ||= FakeManager.new(self)
      end

      class FakeManager
        def initialize(browser)
          @browser = browser
        end

        def timeouts
          @timeouts ||= FakeTimeouts.new(@browser)
        end
      end

      class FakeTimeouts
        def initialize(browser)
          @browser = browser
        end

        def page_load
          @browser.timeout
        end

        def page_load=(t)
          @browser.timeout = t
        end
      end
    end
  end
end

module Ferrum
  class Frame
    module Runtime
      prepend Module.new {
        def evaluate_async(expression, *args)
          # second argument is a timeout in milliseconds
          super(expression, 10 * 1000, *args)
        end
      }
    end
  end
end
```

**Comment by rickychilcott** [comment]
Just wondering if `cuprite` is intended to be supported by this gem? 

We are just starting to use axe in one of our apps -- and this is the only one we use cuprite with.

**Comment by ohrite** [comment]
I got a minimal version of the axe matcher at least running without errors using the following gist: https://gist.github.com/ohrite/242f6babdc346462c6e5e34e6d3a7f89

**Comment by mtomov** [comment]
@ohrite Did you get anywhere with not getting any errors reported with the above gist?

**Comment by ohrite** [comment]
@mtomov honestly, it works well enough that I haven't thought about it in 5 months. Maybe that's a good sign?

**Comment by mtomov** [comment]
Thanks!

> but I'm not getting the error reporting I'd expect

I also tested, and not getting any errors. How come you're saying it's working ?: )

**Comment by AdamJacobson** [comment]
We are seeing similar breaking changes.

```
undefined method `manage' for #<Capybara::Cuprite::Browser:0x00000001166f1050 @options=#<Ferrum::Browser::Options:0x0000000115db5b58 @options...
```

Also saw one for 
```
undefined method `switch_to`
```

but was able to rework the code. It was trying to verify the text of an alert but capybara supports doing 

```
    accept_confirm("Expected alert text") do
      click_button 'Submit'
    end
```

**Comment by NobodysNightmare** [comment]
> Just wondering if cuprite is intended to be supported by this gem?

I'd also be interested in that. Effectively the difference on whether we are reporting a bug or requesting a feature. So far there wasn't a lot of "official response" here. @scottmries is assigned for a year and the issue is "in sprint", but I would be surprised if your sprints lasted for a year ;-)

(needless to say that I'd love axe to play nice together with cuprite)

**Comment by dkniffin** [comment]
Sad to see Cuprite not supported by Axe. I tried to set up axe-core-rspec for my app's test suite, and basically ran into this same issue :/

I am using rspec, capybara and cuprite. So I tried this config:

```
require "axe-rspec"
require "axe-capybara"

AxeCapybara.configure(:chrome) do |c|
end
```

which resulted in:

```
Failure/Error: require "axe-capybara"

LoadError:
  cannot load such file -- selenium-webdriver
```

**Comment by Garbee** [comment]
The Cuprite driver is not stable and was never officially supported by this package set as far as I am aware. Adding support for it, or any changes specifically for it, are not in scope of what we can support.

**Comment by padmavemulapati** [comment]
not seeing any outages now
